INSERT INTO EXCHANGE_RATE(ID, FROM_CURRENCY, TO_CURRENCY, CON_MLTL,PORT) VALUES('USD','USD','INR','76',0);

INSERT INTO EXCHANGE_RATE(ID, FROM_CURRENCY, TO_CURRENCY, CON_MLTL,PORT) VALUES('PAK','PAK','INR','120',0);